drop table tabela1;
drop table tabela2;
drop table tabela3;
drop table tabela4;
drop table tabela5;
drop table tabela6;
drop table tabela7;
drop table tabela8;
drop table tabela9;
drop table tabela10;
drop sequence tab1autoinc;
begin;


create table tabela1 (
	id_wiersza int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY	,
	d1 varchar(20),
	d2 varchar(20)
);

create table tabela2 (
	id_wiersza int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	d1 varchar(20),
	d2 varchar(20)

);

create table tabela3 (
	id_wiersza int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	d1 varchar(20),
	d2 varchar(20)

);

create table tabela4 (
	id_wiersza int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	d1 varchar(20),
	d2 varchar(20)

);

create table tabela5 (
	id_wiersza int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	d1 varchar(20),
	d2 varchar(20)

);

create table tabela6 (
	id_wiersza int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	d1 varchar(20),
	d2 varchar(20)

);

create table tabela7 (
	id_wiersza int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	d1 varchar(20),
	d2 varchar(20)

);

create table tabela8 (
	id_wiersza int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	d1 varchar(20),
	d2 varchar(20)

);

create table tabela9 (
	id_wiersza int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	d1 varchar(20),
	d2 varchar(20)

);

create table tabela10 (
	id_wiersza int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	d1 varchar(20),
	d2 varchar(20)

);


copy tabela1 from stdin with (delimiter '|');
1|"Var1.1T1"|"Var1.2"
2|"Var2.1T1"|"Var2.2"
3|"Var3.1T1"|"Var3.2"
4|"Var4.1T1"|"Var4.2"
5|"Var5.1T1"|"Var5.2"
6|"Var6.1T1"|"Var6.2"
7|"Var7.1T1"|"Var7.2"
8|"Var8.1T1"|"Var8.2"
9|"Var9.1T1"|"Var9.2"
10|"Var10.1T1"|"Var10.2"
11|"Var11.1T1"|"Var11.2"
12|"Var12.1T1"|"Var12.2"
\.

copy tabela2 from stdin with (delimiter '|');
1|"Var1.1T2"|"Var1.2"
2|"Var2.1T2"|"Var2.2"
3|"Var3.1T2"|"Var3.2"
4|"Var4.1T2"|"Var4.2"
5|"Var5.1T2"|"Var5.2"
6|"Var6.1T2"|"Var6.2"
7|"Var7.1T2"|"Var7.2"
8|"Var8.1T2"|"Var8.2"
9|"Var9.1T2"|"Var9.2"
10|"Var10.1T2"|"Var10.2"
11|"Var11.1T2"|"Var11.2"
12|"Var12.1T2"|"Var12.2"
\.

copy tabela3 from stdin with (delimiter '|');
1|"Var1.1T3"|"Var1.2"
2|"Var2.1T3"|"Var2.2"
3|"Var3.1T3"|"Var3.2"
4|"Var4.1T3"|"Var4.2"
5|"Var5.1T3"|"Var5.2"
6|"Var6.1T3"|"Var6.2"
7|"Var7.1T3"|"Var7.2"
8|"Var8.1T3"|"Var8.2"
9|"Var9.1T3"|"Var9.2"
10|"Var10.1T3"|"Var10.2"
11|"Var11.1T3"|"Var11.2"
12|"Var12.1T3"|"Var12.2"
\.

copy tabela4 from stdin with (delimiter '|');
1|"Var1.1T4"|"Var1.2"
2|"Var2.1T4"|"Var2.2"
3|"Var3.1T4"|"Var3.2"
4|"Var4.1T4"|"Var4.2"
5|"Var5.1T4"|"Var5.2"
6|"Var6.1T4"|"Var6.2"
7|"Var7.1T4"|"Var7.2"
8|"Var8.1T4"|"Var8.2"
9|"Var9.1T4"|"Var9.2"
10|"Var10.1T4"|"Var10.2"
11|"Var11.1T4"|"Var11.2"
12|"Var12.1T4"|"Var12.2"
\.

copy tabela5 from stdin with (delimiter '|');
1|"Var1.1T5"|"Var1.2"
2|"Var2.1T5"|"Var2.2"
3|"Var3.1T5"|"Var3.2"
4|"Var4.1T5"|"Var4.2"
5|"Var5.1T5"|"Var5.2"
6|"Var6.1T5"|"Var6.2"
7|"Var7.1T5"|"Var7.2"
8|"Var8.1T5"|"Var8.2"
9|"Var9.1T5"|"Var9.2"
10|"Var10.1T5"|"Var10.2"
11|"Var11.1T5"|"Var11.2"
12|"Var12.1T5"|"Var12.2"
\.

copy tabela6 from stdin with (delimiter '|');
1|"Var1.1T6"|"Var1.2"
2|"Var2.1T6"|"Var2.2"
3|"Var3.1T6"|"Var3.2"
4|"Var4.1T6"|"Var4.2"
5|"Var5.1T6"|"Var5.2"
6|"Var6.1T6"|"Var6.2"
7|"Var7.1T6"|"Var7.2"
8|"Var8.1T6"|"Var8.2"
9|"Var9.1T6"|"Var9.2"
10|"Var10.1T6"|"Var10.2"
11|"Var11.1T6"|"Var11.2"
12|"Var12.1T6"|"Var12.2"
\.

copy tabela7 from stdin with (delimiter '|');
1|"Var1.1T7"|"Var1.2"
2|"Var2.1T7"|"Var2.2"
3|"Var3.1T7"|"Var3.2"
4|"Var4.1T7"|"Var4.2"
5|"Var5.1T7"|"Var5.2"
6|"Var6.1T7"|"Var6.2"
7|"Var7.1T7"|"Var7.2"
8|"Var8.1T7"|"Var8.2"
9|"Var9.1T7"|"Var9.2"
10|"Var10.1T7"|"Var10.2"
11|"Var11.1T7"|"Var11.2"
12|"Var12.1T7"|"Var12.2"
\.

copy tabela8 from stdin with (delimiter '|');
1|"Var1.1T8"|"Var1.2"
2|"Var2.1T8"|"Var2.2"
3|"Var3.1T8"|"Var3.2"
4|"Var4.1T8"|"Var4.2"
5|"Var5.1T8"|"Var5.2"
6|"Var6.1T8"|"Var6.2"
7|"Var7.1T8"|"Var7.2"
8|"Var8.1T8"|"Var8.2"
9|"Var9.1T8"|"Var9.2"
10|"Var10.1T8"|"Var10.2"
11|"Var11.1T8"|"Var11.2"
12|"Var12.1T8"|"Var12.2"
\.

copy tabela9 from stdin with (delimiter '|');
1|"Var1.1T9"|"Var1.2"
2|"Var2.1T9"|"Var2.2"
3|"Var3.1T9"|"Var3.2"
4|"Var4.1T9"|"Var4.2"
5|"Var5.1T9"|"Var5.2"
6|"Var6.1T9"|"Var6.2"
7|"Var7.1T9"|"Var7.2"
8|"Var8.1T9"|"Var8.2"
9|"Var9.1T9"|"Var9.2"
10|"Var10.1T9"|"Var10.2"
11|"Var11.1T9"|"Var11.2"
12|"Var12.1T9"|"Var12.2"
\.

copy tabela10 from stdin with (delimiter '|');
1|"Var1.1T10"|"Var1.2"
2|"Var2.1T10"|"Var2.2"
3|"Var3.1T10"|"Var3.2"
4|"Var4.1T10"|"Var4.2"
5|"Var5.1T10"|"Var5.2"
6|"Var6.1T10"|"Var6.2"
7|"Var7.1T10"|"Var7.2"
8|"Var8.1T10"|"Var8.2"
9|"Var9.1T10"|"Var9.2"
10|"Var10.1T10"|"Var10.2"
11|"Var11.1T10"|"Var11.2"
12|"Var12.1T10"|"Var12.2"
\.


commit;
